#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# build-tools/uml-build.sh — arm64 User-Mode-Linux kernel build (in-container)
#
# Reverse-engineered from the original developer's rootless-650 release:
#   • linux-uml  = kernel 7.2.0-rc4-g8897487c5223 built with CONFIG_UML=y /
#                  CONFIG_UML_ARM64=y / CONFIG_STATIC_LINK=y (Image.config +
#                  build-tools/uml-arm64.config prove the config family).
#                  It is a plain userspace ELF — the UML "vmlinux" — so it is
#                  produced by the normal kernel build with:
#                      make ARCH=um SUBARCH=arm64 ... linux
#   • stub_exe   = the 1.9 KB static arm64 ELF carrying a "uml-userspace"
#                  build-id note; it is the UML build tree's stub binary,
#                  collected out of the same build output.
#
# Public source tree (the original developer's own arm64-UML port — the
# released 7.2.0-rc4-g8897487c5223 banner pins its um-arm64 branch tip):
#   https://github.com/zalexdev/linux-um-arm64   (make ARCH=um SUBARCH=arm64,
#                                                  branch um-arm64)
#
# Usage: uml-build.sh <linux-src-dir> <out-dir>
#        Expects the Android NDK clang toolchain already set up in the env
#        (see the uml-builder stage in the Dockerfile).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SRC="${1:?usage: uml-build.sh <linux-src-dir> <out-dir>}"
OUT="${2:?usage: uml-build.sh <linux-src-dir> <out-dir>}"

RED='\033[1;31m'; GREEN='\033[1;32m'; BLUE='\033[1;34m'; NC='\033[0m'
log()     { printf "${BLUE}==>${NC} %s\n" "$*"; }
success() { printf "${GREEN}SUCCESS:${NC} %s\n" "$*"; }
die()     { printf "${RED}ERROR:${NC} %s\n" "$*" >&2; exit 1; }

[ -f "${SRC}/Makefile" ] || die "Linux source tree not found at ${SRC}"

# ── Tree sanity: the original tree already has everything we need ────────────
# The um-arm64 tip (the released build commit 8897487c5223) exposes
# UML_IOMEM_EMULATION / UML_DMA_EMULATION prompts and no longer adds the
# GCC-only -mabi=lp64 flag, so no source edits are needed — the script only
# hard-fails if it is pointed at a drifted/different tree.
KCONFIG="${SRC}/arch/um/Kconfig"
[ -f "${KCONFIG}" ] || die "${KCONFIG} not found — unexpected tree layout"
grep -A1 '^config UML_IOMEM_EMULATION' "${KCONFIG}" | grep -q 'bool "' \
    || die "${KCONFIG} lacks UML_IOMEM_EMULATION prompt — this is not the um-arm64 tree the original release was built from"
grep -A1 '^config UML_DMA_EMULATION' "${KCONFIG}" | grep -q 'bool "' \
    || die "${KCONFIG} lacks UML_DMA_EMULATION prompt — this is not the um-arm64 tree the original release was built from"
MAKEFILE_UM="${SRC}/arch/arm64/Makefile.um"
[ -f "${MAKEFILE_UM}" ] || die "${MAKEFILE_UM} not found — unexpected tree layout"
if grep -Eq '^[^#]*-mabi=lp64' "${MAKEFILE_UM}"; then
    die "${MAKEFILE_UM} still has -mabi=lp64 — GCC-only flag kills every clang compile; use the zalexdev/linux-um-arm64 um-arm64 branch"
fi
# The stub binary the engine exec's is built and embedded here; the plain
# ELF file is left in the tree, and this script must collect it as stub_exe.
[ -f "${SRC}/arch/um/kernel/skas/Makefile" ] \
    || die "${SRC}/arch/um/kernel/skas/Makefile not found — stub_exe build glue missing"
grep -q 'stub_exe_embed' "${SRC}/arch/um/kernel/skas/Makefile" \
    || die "stub_exe embedding missing from arch/um/kernel/skas/Makefile — wrong tree revision"

JOBS="$(nproc)"
KVER_BASELINE="7.2.0-rc4"
log "Building arm64 UML kernel (baseline ${KVER_BASELINE}, ${JOBS} jobs)"

# ── Toolchain ────────────────────────────────────────────────────────────────
# The released config was generated by Android clang 18.0.3 / LLD 18.0.3
# (CONFIG_CC_VERSION_TEXT / CONFIG_LD_IS_LLD in uml-arm64.config). clang
# 18.0.3 (build 12470979) is the NDK r27c toolchain, and the binary runs as a
# userspace process on Android, so it must link against the bionic static libc
# from the NDK sysroot.
NDK="${NDK:-/opt/ndk}"
LLVM="${LLVM:-${NDK}/toolchains/llvm/prebuilt/linux-x86_64}"
CLANG="${CLANG:-${LLVM}/bin/clang}"
# API 34, not the QEMU stage's 26: the released linux-uml compiles the UML
# user objects cleanly, and those call memfd_create (bionic API 29+) and
# statx (API 30+) — an API-26 sysroot lacks both declarations and dies with
# -Wimplicit-function-declaration (as PR #11's CI run proved). API ≥ 30 is
# therefore the released build's own constraint; 34 is the modern choice
# within the same NDK r27c, and bionic's syscall wrappers are runtime calls,
# so the static binary still runs on older kernels.
API="${API:-34}"
SYSROOT="${LLVM}/sysroot"
# kbuild appends its own CLANG_FLAGS (--target=aarch64-linux-gnu, from
# scripts/Makefile.clang) AFTER our CC — clang applies the LAST --target, and
# both KBUILD_CPPFLAGS (kernel objects) and USER_CFLAGS (arch/um user objects,
# via arch/um/scripts/Makefile.rules) carry it. Re-asserting the target in CC
# does NOT win, because USER_CFLAGS lands inside c_flags after everything on
# the CC command line: arch/arm64/um still dies at archprepare with
# "'asm/types.h' file not found" (the linux-gnu triple drops the NDK's
# usr/include/aarch64-linux-android multiarch dir where asm/types.h lives).
# The clean override is the variable scripts/Makefile.clang itself consults:
#   CLANG_TARGET_FLAGS_um := $(CLANG_TARGET_FLAGS_$(SUBARCH))
# Passing CLANG_TARGET_FLAGS_arm64=... on the make command line (command-line
# variables beat every Makefile assignment, per GNU make) resolves the um
# target to the android triple too, so KBUILD_CPPFLAGS and USER_CFLAGS both
# carry --target=aarch64-linux-androidN. --sysroot stays in CC: it only needs
# to win the command line, and nothing else adds one.
CC_TARGET="--target=aarch64-linux-android${API} --sysroot=${SYSROOT}"
CLANG_TARGET="aarch64-linux-android${API}"

# ── Config ───────────────────────────────────────────────────────────────
# Resolve the checked-in released-config fragment: repo checkouts keep it in
# build-tools/, the Docker stage copies it next to this script.
CONFIG_SRC="${UML_CONFIG:-}"
if [ -z "${CONFIG_SRC}" ]; then
    for cand in "build-tools/uml-arm64.config" "$(dirname "$(readlink -f "$0")")/uml-arm64.config"; do
        if [ -f "${cand}" ]; then CONFIG_SRC="${cand}"; break; fi
    done
fi
[ -n "${CONFIG_SRC}" ] && [ -f "${CONFIG_SRC}" ] \
    || die "uml-arm64.config not found (set UML_CONFIG=/path/to/it)"
log "Using config fragment: ${CONFIG_SRC} ($(wc -l < "${CONFIG_SRC}") lines)"
cp "${CONFIG_SRC}" "${SRC}/.config"

make -C "${SRC}" ARCH=um SUBARCH=arm64 LLVM= olddefconfig
# The fragment must still describe the exact engine we ship.
grep -q '^CONFIG_UML=y'                "${SRC}/.config" || die "CONFIG_UML missing"
grep -q '^CONFIG_UML_ARM64=y'          "${SRC}/.config" || die "CONFIG_UML_ARM64 missing"
grep -q '^CONFIG_STATIC_LINK=y'        "${SRC}/.config" || die "CONFIG_STATIC_LINK missing"
grep -q '^CONFIG_HOSTFS=y'             "${SRC}/.config" || die "CONFIG_HOSTFS missing (rootfs bind)"
grep -q '^CONFIG_UML_NET_VECTOR=y'     "${SRC}/.config" || die "UML_NET_VECTOR missing (original release ships it on)"
grep -q '^CONFIG_RTL8XXXU=y'           "${SRC}/.config" || die "RTL8XXXU missing (USB-WiFi parity)"
grep -q '^CONFIG_ATH9K_HTC=y'          "${SRC}/.config" || die "ATH9K_HTC missing (USB-WiFi parity)"
grep -q '^CONFIG_BLK_DEV_LOOP=y'       "${SRC}/.config" || die "LOOP missing (.img/.iso mount)"

# ── Build ────────────────────────────────────────────────────────────────────
# The UML kernel is built as a userspace binary. CC carries the full Android
# target (--target + NDK sysroot) so the kernel compiles against the NDK
# sysroot and links statically against bionic libc (CONFIG_STATIC_LINK=y adds
# -static -no-pie) — exactly how the released linux-uml runs on stock devices.
# LLVM=1 selects the LLVM binutils family (ld.lld matches CONFIG_LD_IS_LLD=y);
# HOSTCC stays the Debian host gcc for kbuild's own host tools. LLVM is also
# explicitly reset here: an LLVM variable leaked from the environment makes
# kbuild abort with "Invalid value for LLVM".
log "make -j${JOBS} ARCH=um SUBARCH=arm64 (clang/LLD, android${API})"
# KBUILD_BUILD_USER/HOST/TIMESTAMP reproduce the released banner exactly:
#   Linux version 7.2.0-rc4-g8897487c5223 (stryker@images) ... # SMP Thu Jan  1 00:00:00 UTC 1970
# The released binary embeds this exact string (extracted from rootless-650's
# linux-uml), so the builder environment is pinned instead of leaking the CI
# runner's hostname/timestamp into the artifact.
# archprepare compiles USER_OBJS with USER_CFLAGS, which intentionally drops
# KBUILD_CPPFLAGS — so --sysroot only reaches the compiler through CC itself,
# while the --target kbuild appends is redirected to the android triple via
# CLANG_TARGET_FLAGS_arm64 (see the toolchain comment above).
KBUILD_BUILD_USER=stryker KBUILD_BUILD_HOST=images \
KBUILD_BUILD_TIMESTAMP="Thu Jan  1 00:00:00 UTC 1970" \
make -j"${JOBS}" -C "${SRC}" ARCH=um SUBARCH=arm64 \
    CC="${CLANG} ${CC_TARGET}" \
    CLANG_TARGET_FLAGS_arm64="${CLANG_TARGET}" \
    LLVM=1 PATH="${LLVM}/bin:${PATH}" \
    linux
# ── Collect ──────────────────────────────────────────────────────────────────
mkdir -p "${OUT}"
# Kernel binary (the released name is "linux-uml")
cp "${SRC}/linux" "${OUT}/linux-uml"
chmod +x "${OUT}/linux-uml"
# Kernel config dump (parity artifact — the original release ships Image.config)
cp "${SRC}/.config" "${OUT}/linux-uml.config"

# Stub binary: the tiny "uml-userspace" ELF produced by the UML build tree.
# Candidate locations across UML lineages (x86 UML keeps it in the tree root;
# the arm64 port may place it under arch/um or arch/arm64/um):
STUB=""
for cand in \
    "${SRC}/arch/um/kernel/skas/stub_exe" \
    "${SRC}/arch/um/kernel/stub_exe" \
    "${SRC}/arch/um/stub_exe" \
    "${SRC}/arch/arm64/um/stub_exe" \
    "${SRC}/stub_exe"; do
    if [ -f "${cand}" ]; then STUB="${cand}"; break; fi
done
if [ -n "${STUB}" ]; then
    cp "${STUB}" "${OUT}/stub_exe"
    chmod +x "${OUT}/stub_exe"
    log "Stub binary collected: ${STUB} ($(du -h "${OUT}/stub_exe" | cut -f1))"
else
    # Original stub_exe is 1920 bytes and carries a "uml-userspace" build note.
    # Fall back to a search anywhere in the build tree.
    STUB="$(find "${SRC}/arch/um" "${SRC}/arch/arm64" -type f -name 'stub*' -size -16k ! -name '*.o' ! -name '*.S' ! -name '*.c' 2>/dev/null | head -n1 || true)"
    if [ -n "${STUB}" ]; then
        cp "${STUB}" "${OUT}/stub_exe"
        chmod +x "${OUT}/stub_exe"
        log "Stub binary found via search: ${STUB}"
    else
        die "stub_exe was not produced by this tree revision — the rootless_v2 engine needs it. Pin an upstream revision that emits it or ship a cached copy."
    fi
fi

# ── Sanity checks (fail the build rather than shipping a broken engine) ─────
[ -s "${OUT}/linux-uml" ] || die "linux-uml is empty"
SIZE="$(stat -c %s "${OUT}/linux-uml")"
[ "${SIZE}" -gt 10485760 ] || die "linux-uml suspiciously small (${SIZE} bytes)"
if command -v readelf >/dev/null 2>&1; then
    readelf -h "${OUT}/linux-uml" | grep -q 'Machine:.*AArch64' \
        || die "linux-uml is not an arm64 ELF"
    # UML kernels are normal executables, not Image boot payloads.
    readelf -h "${OUT}/linux-uml" | grep -q 'Type:.*EXEC' \
        || die "linux-uml is not an EXEC ELF"
    # Parity with the released binary: statically linked (no PT_INTERP / no
    # dynamic section), exactly like rootless-650's linux-uml.
    if readelf -d "${OUT}/linux-uml" 2>/dev/null | grep -q 'There is no dynamic section'; then :; else
        die "linux-uml is dynamically linked — CONFIG_STATIC_LINK did not hold"
    fi
    # Banner parity: same kernel revision, same pinned build env.
    BANNER="$(strings "${OUT}/linux-uml" | grep -m1 '^Linux version 7\.')"
    case "${BANNER}" in
        "Linux version ${KVER_BASELINE}-g8897487c5223 (stryker@images)"*)
            log "Banner matches the original release: ${BANNER}" ;;
        *) die "Banner mismatch — got '${BANNER}', expected the 7.2.0-rc4-g8897487c5223 (stryker@images) lineage" ;;
    esac
fi
success "arm64 UML kernel built (${SIZE} bytes) → ${OUT}/linux-uml"
success "Config dump → ${OUT}/linux-uml.config"
[ -f "${OUT}/stub_exe" ] && success "Stub → ${OUT}/stub_exe"
exit 0
