#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# build-tools/uml-build.sh — arm64 User-Mode-Linux kernel build (in-container)
#
# Reverse-engineered from the original developer's rootless-650 release:
#   • linux-uml  = kernel 7.2.0-rc4-g8897487c5223 built with CONFIG_UML=y /
#                  CONFIG_UML_ARM64=y / CONFIG_STATIC_LINK=y (Image.config +
#                  build-tools/uml-arm64.config prove the config family).
#                  It is a plain userspace ELF — the UML "vmlinux" — so it is
#                  produced by the normal kernel build with:
#                      make ARCH=um SUBARCH=arm64 ... linux
#   • stub_exe   = the 1.9 KB static arm64 ELF carrying a "uml-userspace"
#                  build-id note; it is the UML build tree's stub binary,
#                  collected out of the same build output.
#
# Public arm64-UML source tree (matches the released 7.2-rc4 lineage):
#   https://github.com/g0l4/uml-for-aarch64   (make ARCH=um SUBARCH=arm64,
#                                              arch/um/configs/arm64_defconfig)
#
# Usage: uml-build.sh <linux-src-dir> <out-dir>
#        Expects the Android NDK clang toolchain already set up in the env
#        (see the uml-builder stage in the Dockerfile).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SRC="${1:?usage: uml-build.sh <linux-src-dir> <out-dir>}"
OUT="${2:?usage: uml-build.sh <linux-src-dir> <out-dir>}"

RED='\033[1;31m'; GREEN='\033[1;32m'; BLUE='\033[1;34m'; NC='\033[0m'
log()     { printf "${BLUE}==>${NC} %s\n" "$*"; }
success() { printf "${GREEN}SUCCESS:${NC} %s\n" "$*"; }
die()     { printf "${RED}ERROR:${NC} %s\n" "$*" >&2; exit 1; }

[ -f "${SRC}/Makefile" ] || die "Linux source tree not found at ${SRC}"

# ── Tree fix: expose UML IOMEM/DMA emulation prompts ─────────────────────────
# The public arm64-UML tree keeps UML_IOMEM_EMULATION / UML_DMA_EMULATION
# invisible — they can only be enabled via UML_PCI's selects. The released
# rootless-650 Image.config sets both directly (with INDIRECT_IOMEM, USB,
# RTL8XXXU/ATH9K_HTC and no PCI machinery), so the original tree exposed
# prompts for them. Without this fix olddefconfig silently drops
# CONFIG_UML_IOMEM_EMULATION, NO_IOMEM stays on, HAS_IOMEM/USB_SUPPORT become
# unreachable, and the USB-WiFi drivers fall out of the config.
# Edited in place with python3 (the builder image has no `patch` binary and
# an external .patch blob proved fragile). Idempotent: skipped when the
# prompts are already present.
KCONFIG="${SRC}/arch/um/Kconfig"
[ -f "${KCONFIG}" ] || die "${KCONFIG} not found — unexpected tree layout"
if ! grep -A1 '^config UML_IOMEM_EMULATION' "${KCONFIG}" | grep -q 'bool "'; then
    log "Exposing UML IOMEM/DMA emulation prompts in ${KCONFIG}"
    python3 - "${KCONFIG}" <<'PYEOF'
import sys
path = sys.argv[1]
s = open(path).read()
s = s.replace("config UML_DMA_EMULATION\n\tbool\n",
              "config UML_DMA_EMULATION\n\tbool \"UML DMA emulation\"\n")
s = s.replace("config UML_IOMEM_EMULATION\n\tbool\n",
              "config UML_IOMEM_EMULATION\n\tbool \"UML IOMEM emulation\"\n")
open(path, "w").write(s)
PYEOF
fi
# Fail hard if the prompts are still missing: proceeding silently would ship
# an engine without USB-WiFi drivers.
grep -A1 '^config UML_IOMEM_EMULATION' "${KCONFIG}" | grep -q 'bool "' \
    || die "${KCONFIG} lacks UML_IOMEM_EMULATION prompt — tree drifted, update the inline edit"
grep -A1 '^config UML_DMA_EMULATION' "${KCONFIG}" | grep -q 'bool "' \
    || die "${KCONFIG} lacks UML_DMA_EMULATION prompt — tree drifted, update the inline edit"

JOBS="$(nproc)"
KVER_BASELINE="7.2.0-rc4"
log "Building arm64 UML kernel (baseline ${KVER_BASELINE}, ${JOBS} jobs)"

# ── Toolchain ────────────────────────────────────────────────────────────────
# The released config was generated by Android clang 18 / LLD 18
# (CONFIG_CC_VERSION_TEXT / CONFIG_LD_IS_LLD in uml-arm64.config), and the
# binary runs as a userspace process on Android, so it must link against the
# bionic static libc from the NDK sysroot.
NDK="${NDK:-/opt/ndk}"
LLVM="${LLVM:-${NDK}/toolchains/llvm/prebuilt/linux-x86_64}"
CLANG="${CLANG:-${LLVM}/bin/clang}"
API="${API:-26}"
SYSROOT="${LLVM}/sysroot"
CC_TARGET="--target=aarch64-linux-android${API} --sysroot=${SYSROOT}"

# ── Config ───────────────────────────────────────────────────────────────
# Resolve the checked-in released-config fragment: repo checkouts keep it in
# build-tools/, the Docker stage copies it next to this script.
CONFIG_SRC="${UML_CONFIG:-}"
if [ -z "${CONFIG_SRC}" ]; then
    for cand in "build-tools/uml-arm64.config" "$(dirname "$(readlink -f "$0")")/uml-arm64.config"; do
        if [ -f "${cand}" ]; then CONFIG_SRC="${cand}"; break; fi
    done
fi
[ -n "${CONFIG_SRC}" ] && [ -f "${CONFIG_SRC}" ] \
    || die "uml-arm64.config not found (set UML_CONFIG=/path/to/it)"
log "Using config fragment: ${CONFIG_SRC} ($(wc -l < "${CONFIG_SRC}") lines)"
cp "${CONFIG_SRC}" "${SRC}/.config"

make -C "${SRC}" ARCH=um SUBARCH=arm64 LLVM= olddefconfig
# The fragment must still describe the exact engine we ship.
grep -q '^CONFIG_UML=y'                "${SRC}/.config" || die "CONFIG_UML missing"
grep -q '^CONFIG_UML_ARM64=y'          "${SRC}/.config" || die "CONFIG_UML_ARM64 missing"
grep -q '^CONFIG_STATIC_LINK=y'        "${SRC}/.config" || die "CONFIG_STATIC_LINK missing"
grep -q '^CONFIG_HOSTFS=y'             "${SRC}/.config" || die "CONFIG_HOSTFS missing (rootfs bind)"
grep -q '^CONFIG_RTL8XXXU=y'           "${SRC}/.config" || die "RTL8XXXU missing (USB-WiFi parity)"
grep -q '^CONFIG_ATH9K_HTC=y'          "${SRC}/.config" || die "ATH9K_HTC missing (USB-WiFi parity)"
grep -q '^CONFIG_BLK_DEV_LOOP=y'       "${SRC}/.config" || die "LOOP missing (.img/.iso mount)"

# ── Build ────────────────────────────────────────────────────────────────────
# The UML kernel is built as a userspace binary. CC carries the full Android
# target (--target + NDK sysroot) so the kernel compiles against the NDK
# sysroot and links statically against bionic libc (CONFIG_STATIC_LINK=y adds
# -static -no-pie) — exactly how the released linux-uml runs on stock devices.
# LLVM=1 selects the LLVM binutils family (ld.lld matches CONFIG_LD_IS_LLD=y);
# HOSTCC stays the Debian host gcc for kbuild's own host tools. LLVM is also
# explicitly reset here: an LLVM variable leaked from the environment makes
# kbuild abort with "Invalid value for LLVM".
log "make -j${JOBS} ARCH=um SUBARCH=arm64 (clang/LLD, android${API})"
make -j"${JOBS}" -C "${SRC}" ARCH=um SUBARCH=arm64 \
    CC="${CLANG} ${CC_TARGET}" \
    LLVM=1 PATH="${LLVM}/bin:${PATH}" \
    linux

# ── Collect ──────────────────────────────────────────────────────────────────
mkdir -p "${OUT}"
# Kernel binary (the released name is "linux-uml")
cp "${SRC}/linux" "${OUT}/linux-uml"
chmod +x "${OUT}/linux-uml"
# Kernel config dump (parity artifact — the original release ships Image.config)
cp "${SRC}/.config" "${OUT}/linux-uml.config"

# Stub binary: the tiny "uml-userspace" ELF produced by the UML build tree.
# Candidate locations across UML lineages (x86 UML keeps it in the tree root;
# the arm64 port may place it under arch/um or arch/arm64/um):
STUB=""
for cand in \
    "${SRC}/arch/um/kernel/skas/stub_exe" \
    "${SRC}/arch/um/kernel/stub_exe" \
    "${SRC}/arch/um/stub_exe" \
    "${SRC}/arch/arm64/um/stub_exe" \
    "${SRC}/stub_exe"; do
    if [ -f "${cand}" ]; then STUB="${cand}"; break; fi
done
if [ -n "${STUB}" ]; then
    cp "${STUB}" "${OUT}/stub_exe"
    chmod +x "${OUT}/stub_exe"
    log "Stub binary collected: ${STUB} ($(du -h "${OUT}/stub_exe" | cut -f1))"
else
    # Original stub_exe is 1920 bytes and carries a "uml-userspace" build note.
    # Fall back to a search anywhere in the build tree.
    STUB="$(find "${SRC}/arch/um" "${SRC}/arch/arm64" -type f -name 'stub*' -size -16k 2>/dev/null | head -n1 || true)"
    if [ -n "${STUB}" ]; then
        cp "${STUB}" "${OUT}/stub_exe"
        chmod +x "${OUT}/stub_exe"
        log "Stub binary found via search: ${STUB}"
    else
        die "stub_exe was not produced by this tree revision — the rootless_v2 engine needs it. Pin an upstream revision that emits it or ship a cached copy."
    fi
fi

# ── Sanity checks (fail the build rather than shipping a broken engine) ─────
[ -s "${OUT}/linux-uml" ] || die "linux-uml is empty"
SIZE="$(stat -c %s "${OUT}/linux-uml")"
[ "${SIZE}" -gt 10485760 ] || die "linux-uml suspiciously small (${SIZE} bytes)"
if command -v readelf >/dev/null 2>&1; then
    readelf -h "${OUT}/linux-uml" | grep -q 'Machine:.*AArch64' \
        || die "linux-uml is not an arm64 ELF"
    # UML kernels are normal executables, not Image boot payloads.
    readelf -h "${OUT}/linux-uml" | grep -q 'Type:.*EXEC' \
        || die "linux-uml is not an EXEC ELF"
fi
success "arm64 UML kernel built (${SIZE} bytes) → ${OUT}/linux-uml"
success "Config dump → ${OUT}/linux-uml.config"
[ -f "${OUT}/stub_exe" ] && success "Stub → ${OUT}/stub_exe"
exit 0
